<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curriculum [
	<!ELEMENT curriculum (nombre,apellidos,fecha_nacimiento,residencia,datos_contacto,descripcion,competencias,formacion_academica,experiencia_profesional)>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT apellidos (#PCDATA)>
	<!ELEMENT fecha_nacimiento (#PCDATA)>
	<!ELEMENT residencia (direccion,ciudad,cp,pais)>
	<!ELEMENT direccion (#PCDATA)>
	<!ELEMENT ciudad (#PCDATA)>
	<!ELEMENT cp (#PCDATA)>
	<!ELEMENT pais (#PCDATA)>
	<!ELEMENT datos_contacto (telefono,correo)>
	<!ELEMENT telefono (#PCDATA)>
	<!ELEMENT correo (#PCDATA)>
	<!ELEMENT descripcion (#PCDATA)>
	<!ELEMENT competencias (competencia+)>
	<!ELEMENT competencia (nombre,nivel)>
	<!ELEMENT nivel (#PCDATA)>
	<!ELEMENT formacion_academica (titulacion,centro_formacion,ano_titulacion)>
	<!ELEMENT titulacion (#PCDATA)>
	<!ELEMENT centro_formacion (#PCDATA)>
	<!ELEMENT ano_titulacion (#PCDATA)>
	<!ELEMENT experiencia_profesional (puesto,empresa,ano_inicio,ano_finalizacion)>
	<!ELEMENT puesto (#PCDATA)>
	<!ELEMENT empresa (#PCDATA)>
	<!ELEMENT ano_inicio (#PCDATA)>
	<!ELEMENT ano_finalizacion (#PCDATA)>
	
]>

<curriculum>
    <nombre>Jesús</nombre>
    <apellidos>Ramirez León</apellidos>
    <fecha_nacimiento>22/11/2000</fecha_nacimiento>

    <residencia>
        <direccion>Calle 13 Rúa del percebe</direccion>
        <ciudad>Algeciras</ciudad>
        <cp>11201</cp>
        <pais>España</pais>
    </residencia>
    
    <datos_contacto>
        <telefono>666767676</telefono>
        <correo>jesusuin.jesusan@gmail.com</correo>
    </datos_contacto>
    
    <descripcion>
        Graduado en Ingeniería Informática con experiencia en desarrollo de software y sistemas.
    </descripcion>
    
    <competencias>
        <competencia>
            <nombre>Desarrollo de Aplicaciones Web</nombre>
            <nivel>Escaso</nivel>
        </competencia>
        <competencia>
            <nombre>Programación en Python</nombre>
            <nivel>Intermedio</nivel>
        </competencia>
    </competencias>
    
    <formacion_academica>
        <titulacion>Ingeniería Informática</titulacion>
        <centro_formacion>Universidad de Algeciras</centro_formacion>
        <ano_titulacion>2005</ano_titulacion>
    </formacion_academica>
    
    <experiencia_profesional>
        <puesto>Desarrollador de Software</puesto>
        <empresa>Algoritmos Algeciras</empresa>
        <ano_inicio>2013</ano_inicio>
        <ano_finalizacion>Activo</ano_finalizacion>
    </experiencia_profesional>
</curriculum>