=== Amaado/DAM1_archives/lmsxi/Trimestre 2/Ejercicios/amado_cibreiro_andres_LM46_sub43_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo"></xs:element>
                            <xs:element name="autor" maxOccurs="unbounded"></xs:element>
                            <xs:element name="anho_publicacion"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="num_paginas" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Amaado/DAM1_archives/lmsxi/Trimestre 2/Ejercicios/amado_cibreiro_andres_LM43_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    <!DOCTYPE biblioteca [
	<!ELEMENT biblioteca (libro+)>
	<!ELEMENT libro (titulo,autor+,anho_publicacion)>
    <!ATTLIST libro num_paginas CDATA "Desconocido">
	<!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT anho_publicacion (#PCDATA)>
]>
-->
<biblioteca xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="amado_cibreiro_andres_LM46_sub43_1.xsd">
    <libro num_paginas="400">
        <titulo>Los miserables</titulo>
        <autor>Victor Hugo</autor>
        <anho_publicacion>1862</anho_publicacion>
    </libro>
    <libro num_paginas="50">
        <titulo>El caos reptante</titulo>
        <autor>H.P Lovecraft</autor>
        <autor>Winifred V. Jackson</autor>
        <anho_publicacion>1862</anho_publicacion>
    </libro>
</biblioteca>
