<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE vueling [
	<!ELEMENT vueling (viaje)>
	<!ELEMENT viaje (datos_clientes,fechas,lugares,precio)>
	<!ELEMENT datos_clientes (nombre,apellidos)>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT apellidos (#PCDATA)>
	<!ELEMENT fechas (fecha_inicio,fecha_fin)>
	<!ELEMENT fecha_inicio (#PCDATA)>
	<!ELEMENT fecha_fin (#PCDATA)>
	<!ELEMENT lugares (lugar_origen,lugar_destino)>
	<!ELEMENT lugar_origen (#PCDATA)>
	<!ELEMENT lugar_destino (nombre_ciudad,nombre_hotel,num_noches)>
	<!ELEMENT nombre_ciudad (#PCDATA)>
	<!ELEMENT nombre_hotel (#PCDATA)>
	<!ELEMENT num_noches (#PCDATA)>
	<!ELEMENT precio (#PCDATA)>
]>

<vueling>
	<viaje>
		<datos_clientes>
			<nombre>Francisco</nombre>
			<apellidos>Rede Lapoli</apellidos>
		</datos_clientes>
		<fechas>
			<fecha_inicio>11/01/2024</fecha_inicio>
			<fecha_fin>11/01/2024</fecha_fin>
		</fechas>
		<lugares>
			<lugar_origen>IES Antón Losada Dieguez, Aula 112</lugar_origen>
			<lugar_destino>
				<nombre_ciudad>San Francisco</nombre_ciudad>
				<nombre_hotel>A NOSSA SAMBITA</nombre_hotel>
				<num_noches>3</num_noches>
			</lugar_destino>
		</lugares>
		<precio>2000€</precio>
	</viaje>
</vueling>