=== Amaado/DAM1_archives/lmsxi/Trimestre 2/Ejercicios/amado_cibreiro_andres_LM47_3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="curso" type="cursoType"></xs:element>

        <xs:complexType name="cursoType">
            <xs:sequence>
                <xs:element name="num" type="xs:string"></xs:element>
                <xs:element name="horario_recreo" type="horario_recreoType"></xs:element>
                <xs:element name="materias" type="materiasType"></xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="horario_recreoType">
            <xs:sequence>
                <xs:element name="primero" type="recreoType"></xs:element>
                <xs:element name="segundo" type="recreoType"></xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="recreoType">
            <xs:sequence>
                <xs:element name="hora_inicio" minOccurs="1" maxOccurs="1" type="filtro_hora"></xs:element>
                <xs:element name="hora_fin" minOccurs="1" maxOccurs="1" type="filtro_hora"></xs:element>
            </xs:sequence>
        </xs:complexType>


        <xs:complexType name="materiasType">
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="materia" type="materiaType"></xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="materiaType">
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"></xs:element>
                <xs:element name="profesor" type="xs:string"></xs:element>
                <xs:element name="horario" type="horarioType"></xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="horarioType">
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="dia" type="diaType"></xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="diaType">
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="sesion" type="sesionType"></xs:element>
            </xs:sequence>
            <xs:attribute name="dia" type="dias_semana"></xs:attribute>
        </xs:complexType>

        <xs:complexType name="sesionType">
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="aula" minOccurs="1" maxOccurs="1" type="filtro_aula"></xs:element>
                <xs:element name="hora_inicio" minOccurs="1" maxOccurs="1" type="filtro_hora"></xs:element>
                <xs:element name="hora_fin" minOccurs="1" maxOccurs="1" type="filtro_hora"></xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:simpleType name="dias_semana">
            <xs:restriction base="xs:string">
                <xs:enumeration value="Lunes" />
                <xs:enumeration value="Martes" />
                <xs:enumeration value="Miercoles" />
                <xs:enumeration value="Jueves" />
                <xs:enumeration value="Viernes" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="filtro_hora">
            <xs:restriction base="xs:string">
                <xs:pattern value="([07-9]|1[0-9]|2[0-2]):(00|10|20|30|40|50)" />
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="filtro_aula">
            <xs:restriction base="xs:string">
                <xs:pattern value="[0-9]{3}" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

</xs:schema>

=== Amaado/DAM1_archives/lmsxi/Trimestre 2/Ejercicios/amado_cibreiro_andres_LM47_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<curso xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="amado_cibreiro_andres_LM47_3.xsd">
    <num>2023-24</num>
    <horario_recreo>
        <primero>
            <hora_inicio>17:10</hora_inicio>
            <hora_fin>17:30</hora_fin>
        </primero>

        <segundo>
            <hora_inicio>20:00</hora_inicio>
            <hora_fin>20:20</hora_fin>
        </segundo>

    </horario_recreo>

    <materias>
        <materia>
            <nombre>Linguaxes de marcas e sistemas de xestión de información</nombre>
            <profesor>Miguel Ixem Couto Pérez</profesor>
            <horario>
                <dia dia="Lunes">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>18:20</hora_inicio>
                        <hora_fin>19:10</hora_fin>
                    </sesion>
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>19:10</hora_inicio>
                        <hora_fin>20:00</hora_fin>
                    </sesion>
                </dia>

                <dia dia="Jueves">
                    <sesion>
                        <aula>105</aula>
                        <hora_inicio>14:40</hora_inicio>
                        <hora_fin>15:30</hora_fin>
                    </sesion>
                    <sesion>
                        <aula>105</aula>
                        <hora_inicio>15:30</hora_inicio>
                        <hora_fin>16:20</hora_fin>
                    </sesion>
                </dia>

                <dia dia="Viernes">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>17:30</hora_inicio>
                        <hora_fin>18:20</hora_fin>
                    </sesion>
                </dia>
            </horario>
        </materia>

        <materia>
            <nombre>Bases de datos</nombre>
            <profesor>Miguel Ixem Couto Pérez</profesor>
            <horario>
                <dia dia="Lunes">
                    <sesion>
                        <aula>105</aula>
                        <hora_inicio>15:30</hora_inicio>
                        <hora_fin>16:20</hora_fin>
                    </sesion>
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>16:20</hora_inicio>
                        <hora_fin>17:10</hora_fin>
                    </sesion>
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>17:30</hora_inicio>
                        <hora_fin>18:20</hora_fin>
                    </sesion>
                </dia>

                <dia dia="Martes">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>19:10</hora_inicio>
                        <hora_fin>20:00</hora_fin>
                    </sesion>
                </dia>

                <dia dia="Miercoles">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>16:20</hora_inicio>
                        <hora_fin>17:10</hora_fin>
                    </sesion>
                </dia>

                <dia dia="Jueves">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>16:20</hora_inicio>
                        <hora_fin>17:10</hora_fin>
                    </sesion>
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>17:30</hora_inicio>
                        <hora_fin>18:20</hora_fin>
                    </sesion>
                </dia>
            </horario>
        </materia>

        <materia>
            <nombre>Sistemas informáticos</nombre>
            <profesor>Fernando Gómez Folgar</profesor>
            <horario>
                <dia dia="Lunes">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>20:20</hora_inicio>
                        <hora_fin>21:10</hora_fin>
                    </sesion>
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>21:10</hora_inicio>
                        <hora_fin>22:00</hora_fin>
                    </sesion>
                </dia>

                <dia dia="Martes">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>16:20</hora_inicio>
                        <hora_fin>17:10</hora_fin>
                    </sesion>
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>17:10</hora_inicio>
                        <hora_fin>18:20</hora_fin>
                    </sesion>
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>18:20</hora_inicio>
                        <hora_fin>19:10</hora_fin>
                    </sesion>
                </dia>

                <dia dia="Viernes">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>20:20</hora_inicio>
                        <hora_fin>21:10</hora_fin>
                    </sesion>
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>21:10</hora_inicio>
                        <hora_fin>22:00</hora_fin>
                    </sesion>
                </dia>
            </horario>
        </materia>

        <materia>
            <nombre>Formación e orientación laboral</nombre>
            <profesor>Mónica Arca Vilariño</profesor>
            <horario>

                <dia dia="Martes">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>15:30</hora_inicio>
                        <hora_fin>16:20</hora_fin>
                    </sesion>
                </dia>

                <dia dia="Miercoles">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>15:30</hora_inicio>
                        <hora_fin>16:20</hora_fin>
                    </sesion>
                </dia>

                <dia dia="Viernes">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>15:30</hora_inicio>
                        <hora_fin>16:20</hora_fin>
                    </sesion>
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>16:20</hora_inicio>
                        <hora_fin>17:10</hora_fin>
                    </sesion>
                </dia>
            </horario>
        </materia>

        <materia>
            <nombre>Programación</nombre>
            <profesor>Rosalia Calleja Gómez</profesor>
            <horario>

                <dia dia="Martes">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>20:20</hora_inicio>
                        <hora_fin>21:10</hora_fin>
                    </sesion>
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>21:10</hora_inicio>
                        <hora_fin>22:00</hora_fin>
                    </sesion>
                </dia>

                <dia dia="Miercoles">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>17:30</hora_inicio>
                        <hora_fin>18:20</hora_fin>
                    </sesion>
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>18:20</hora_inicio>
                        <hora_fin>19:10</hora_fin>
                    </sesion>
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>19:10</hora_inicio>
                        <hora_fin>20:00</hora_fin>
                    </sesion>
                </dia>

                <dia dia="Jueves">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>19:10</hora_inicio>
                        <hora_fin>20:00</hora_fin>
                    </sesion>
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>20:20</hora_inicio>
                        <hora_fin>21:10</hora_fin>
                    </sesion>
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>21:10</hora_inicio>
                        <hora_fin>22:00</hora_fin>
                    </sesion>
                </dia>

                <dia dia="Viernes">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>18:20</hora_inicio>
                        <hora_fin>19:10</hora_fin>
                    </sesion>
                </dia>
            </horario>
        </materia>

        <materia>
            <nombre>Contornos de desnvolvemento</nombre>
            <profesor>Antón Orduna Viguera</profesor>
            <horario>

                <dia dia="Miercoles">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>20:20</hora_inicio>
                        <hora_fin>21:10</hora_fin>
                    </sesion>
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>21:10</hora_inicio>
                        <hora_fin>22:00</hora_fin>
                    </sesion>
                </dia>

                <dia dia="Jueves">
                    <sesion>
                        <aula>112</aula>
                        <hora_inicio>18:20</hora_inicio>
                        <hora_fin>19:10</hora_fin>
