=== Amaado/DAM1_archives/lmsxi/Trimestre 2/Ejercicios/amado_cibreiro_andres_LM47_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pedidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pedido" type="xs:string" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="nombre_cliente" type="xs:string"></xs:element>
                        </xs:choice>
                        <xs:choice>
                            <xs:element name="mesa" type="xs:integer"></xs:element>
                        </xs:choice>
                        <xs:choice>
                            <xs:element name="fecha" type="xs:string"></xs:element>
                        </xs:choice>
                        <xs:choice>
                            <xs:element name="contenido">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:element name="hamburguesa" type="xs:string">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="nombre" type="xs:string"></xs:element>
                                                    <xs:element name="numero" type="xs:integer"></xs:element>
                                                    <xs:element name="precio" type="xs:string"></xs:element>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                    <xs:choice>
                                        <xs:element name="complemento" type="xs:string">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="nombre" type="xs:string"></xs:element>
                                                    <xs:element name="numero" type="xs:integer"></xs:element>
                                                    <xs:element name="precio" type="xs:string"></xs:element>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                    <xs:attribute name="codigo" type="xs:integer"></xs:attribute>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Amaado/DAM1_archives/lmsxi/Trimestre 2/Ejercicios/amado_cibreiro_andres_LM47_1.xml
<?xml version="1.0" encoding="UTF-8"?>

<pedidos  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="amado_cibreiro_andres_LM47_1.xsd">
    <pedido codigo="142">
        <nombre_cliente>Juan Perez Castellon</nombre_cliente>
        <mesa>4</mesa>
        <fecha>22/11/2023</fecha>
        <contenido>
            <hamburguesa>
                <nombre>Burguer-Kangreburger</nombre>
                <numero>3</numero>
                <precio>20$</precio>
            </hamburguesa>
            <complemento>
                <nombre>Agua mineral</nombre>
                <numero>1</numero>
                <precio>1,5$</precio>
            </complemento>
        </contenido>
    </pedido>
</pedidos>
