<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE paises [
	<!ELEMENT paises (pais+)>
    <!ELEMENT pais (nombre,continente,capital)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT continente (#PCDATA)>
    <!ELEMENT capital (#PCDATA)>
]>

<paises>
    <pais>
        <nombre>España</nombre>
        <continente>Europa</continente>
        <capital>Madrid</capital>
    </pais>
    <pais>
        <nombre>Francia</nombre>
        <continente>Europa</continente>
        <capital>París</capital>
    </pais>
    <pais>
        <nombre>Portugal</nombre>
        <continente>Europa</continente>
        <capital>Lisboa</capital>
    </pais>
</paises>